# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13b70dc0eb9c6969ffc1403217db21578f3569798c3251e8412a620f858bfe271ec8efa47902c5bacb17a06dc203c9c6741a5c3032397580bef8001fb695c37c

test:
  secret_key_base: 5177117ce49100e87cc1eaf211aa62e4dccb7480aa99465f455cb01782d2828ba456370f8437358e2c3e85387a899d8795b79c6696597088503071283da95dd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
